### ISSUE TITLE
为什么要使用Docker和两个容器

### ISSUE THREAD

**Issue by LINRONGG** [XetRAHF/TiZi_AcrossTheGreatWall#1]
两台服务器是为了运行两个容器。。。那么。。。为啥要运行两个容器？是因为作为备用还是有其他原因？

**Comment by XetRAHF** [comment]
* 因为这样可以开两个端口
| 外部端口 | 内部端口 |
|----------|----------|
| 80 | 8989 |
| 443 | 8989 |
* 还有一个好处就是这样的话两个端口可以做不同的配置相互不影响（比如不同的密码）

**Comment by LINRONGG** [comment]
这样做会不会较低移动对ssr的干扰。。。

**Comment by XetRAHF** [comment]
* 那篇人工智能论文只检测SS不检测SSR
* 使用80/443这样的常用端口能更好的避免检测出来

**Comment by LINRONGG** [comment]
但是 自从十月份 十九大以来。。。我广州移动每次打开ssr几分钟就连不上了

**Comment by XetRAHF** [comment]
这个和选择的服务器地区有关
我们之前在美国东部的服务器一直特别不好，19大之后就ping不通了，后来我们重新部署了其他地方的服务器，选择了两个不同的地点（亚洲，美国西部）然后问题就解决了

**Comment by XetRAHF** [comment]
而且防火墙的屏蔽看似不是对单个ip的屏蔽，而是对整个地区的屏蔽
