### ISSUE TITLE
DO-512mb-1gb CentOS 6.9 x64 docker容器内执行报错

### ISSUE THREAD

**Issue by youtao531** [XetRAHF/TiZi_AcrossTheGreatWall#2]
[root@5bb70295da00 /]# yum update -y && yum install -y wget net-tools vim && wget https://raw.githubusercontent.com/xetra-enterprize/shadowsocks_install/master/shadowsocks-all.sh && bash ./shadowsocks-all.sh
Loaded plugins: fastestmirror, ovl
Setting up Update Process
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os&infra=container error was
14: PYCURL ERROR 7 - "Failed to connect to 2001:1b48:203::4:10: Network is unreachable"
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
[root@5bb70295da00 /]#

**Comment by XetRAHF** [comment]
# 哪里出的问题
```
yum update
```
# 如何解决
```
yum clean all
yum check
yum erase apf
yum upgrade
```
# 参考
[Stack Exchange Question](https://unix.stackexchange.com/questions/109585/yum-update-fails-error-cannot-retrieve-repository-metadata-repomd-xml-for-re)

**Comment by youtao531** [comment]
已解决，感谢。
